/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for proca_certificate
 */
#include <linux/asn1_ber_bytecode.h>
#include "proca_certificate-asn1.h"

enum proca_certificate_actions {
	ACT_proca_certificate_get_app_name = 0,
	ACT_proca_certificate_get_five_signature_hash = 1,
	NR__proca_certificate_actions = 2
};

static const asn1_action_t proca_certificate_action_table[NR__proca_certificate_actions] = {
	[   0] = proca_certificate_get_app_name,
	[   1] = proca_certificate_get_five_signature_hash,
};

static const unsigned char proca_certificate_machine[] = {
	// PaCertificate
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	// PaData
	[   2] =  ASN1_OP_MATCH,
	[   3] =  _tag(UNIV, CONS, SEQ),
	[   4] =   ASN1_OP_MATCH,		// paVersion
	[   5] =   _tag(UNIV, PRIM, INT),
	[   6] =   ASN1_OP_MATCH,		// paFlags
	[   7] =   _tag(UNIV, PRIM, INT),
	[   8] =   ASN1_OP_MATCH,		// paKeyId
	[   9] =   _tag(UNIV, PRIM, INT),
	[  10] =   ASN1_OP_MATCH,		// paId
	[  11] =   _tag(UNIV, PRIM, OTS),
	[  12] =   ASN1_OP_MATCH_ACT,		// paAppName
	[  13] =   _tag(UNIV, PRIM, OTS),
	[  14] =   _action(ACT_proca_certificate_get_app_name),
	[  15] =   ASN1_OP_MATCH_ACT,		// fiveSignatureHash
	[  16] =   _tag(UNIV, PRIM, OTS),
	[  17] =   _action(ACT_proca_certificate_get_five_signature_hash),
	[  18] =  ASN1_OP_END_SEQ,
	[  19] =  ASN1_OP_MATCH,		// signature
	[  20] =  _tag(UNIV, PRIM, OTS),
	[  21] = ASN1_OP_END_SEQ,
	[  22] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder proca_certificate_decoder = {
	.machine = proca_certificate_machine,
	.machlen = sizeof(proca_certificate_machine),
	.actions = proca_certificate_action_table,
};
