/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for proca_certificate
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder proca_certificate_decoder;

extern int proca_certificate_get_app_name(void *, size_t, unsigned char, const void *, size_t);
extern int proca_certificate_get_five_signature_hash(void *, size_t, unsigned char, const void *, size_t);

